import { useParams } from 'react-router-dom';
import { GameCard } from '../components/GameCard';

// Extended game data for each genre
const GENRE_GAMES = {
  'free-to-play': [
    {
      id: 'f2p-1',
      title: 'Counter Strike - 2',
      description: 'Fast-paced multiplayer shooter with futuristic weapons',
      price: 25.99,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDgSjZtCPN97fSiRYgcACS6Qz3ntK0bouXXw&s',
      developer: 'Cyber Games',
      publisher: 'Digital Entertainment',
      releaseDate: '2024-03-01',
      genres: ['Free To Play', 'Action', 'Shooter'],
      tags: ['Multiplayer', 'FPS', 'Competitive'],
      rating: 4.5,
      playerCount: 25000,
      features: ['Cross-platform', 'Competitive Leagues', 'Weekly Events'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'Spanish', 'Chinese']
    },
    {
      "id": "f2p-2",
      "title": "Fortnite",
      "description": "Battle Royale game with building mechanics and vibrant visuals",
      "price": 59.99,
      "image": "https://img.freepik.com/premium-photo/fortnite-wallpaper-4k-gaming-wallpaper_1108314-494784.jpg",
      "developer": "Epic Games",
      "publisher": "Epic Games",
      "releaseDate": "2024-07-01",
      "genres": ["Free To Play", "Battle Royale", "Action"],
      "tags": ["Multiplayer", "Battle Royale", "Building"],
      "rating": 4.6,
      "playerCount": 200000,
      "features": ["Cross-platform", "Building Mechanics", "Seasonal Events"],
      "operatingSystem": ["Windows", "MacOS", "PlayStation", "Xbox"],
      "languages": ["English", "Spanish", "French", "German"]
    },
    {
      "id": "f2p-3",
      "title": "Apex Legends",
      "description": "Fast-paced Battle Royale game with unique heroes and abilities",
      "price": 39.99,
      "image": "https://i.redd.it/s6pti85u9cy41.jpg",
      "developer": "Respawn Entertainment",
      "publisher": "Electronic Arts",
      "releaseDate": "2024-04-01",
      "genres": ["Free To Play", "Battle Royale", "Action"],
      "tags": ["Multiplayer", "Battle Royale", "Hero-based"],
      "rating": 4.7,
      "playerCount": 150000,
      "features": ["Unique Heroes", "Cross-platform", "Ranked Mode"],
      "operatingSystem": ["Windows", "PlayStation", "Xbox"],
      "languages": ["English", "Spanish", "French"]
    },
    {
      "id": "f2p-4",
      "title": "Call of Duty: Warzone",
      "description": "Battle Royale mode in the Call of Duty franchise with intense firefights",
      "price": 49.99,
      "image": "https://cdn.images.express.co.uk/img/dynamic/143/590x/1467524_1.jpg",
      "developer": "Infinity Ward",
      "publisher": "Activision",
      "releaseDate": "2024-05-15",
      "genres": ["Free To Play", "Battle Royale", "Shooter"],
      "tags": ["Multiplayer", "Competitive", "FPS"],
      "rating": 4.6,
      "playerCount": 120000,
      "features": ["Cross-platform", "Realistic Combat", "Team-based"],
      "operatingSystem": ["Windows", "PlayStation", "Xbox"],
      "languages": ["English", "Spanish", "German"]
    },
    {
      "id": "f2p-5",
      "title": "Valorant",
      "description": "Tactical 5v5 shooter with hero-based abilities",
      "price": 59.99,
      "image": "https://wallpapers.com/images/featured/valorant-305kescxw5dpup7y.jpg",
      "developer": "Riot Games",
      "publisher": "Riot Games",
      "releaseDate": "2024-06-01",
      "genres": ["Free To Play", "Shooter", "Tactical"],
      "tags": ["Multiplayer", "Competitive", "Team-based"],
      "rating": 4.8,
      "playerCount": 50000,
      "features": ["Hero Abilities", "Cross-platform", "Ranked Mode"],
      "operatingSystem": ["Windows"],
      "languages": ["English", "Spanish", "French"]
    },
    {
      "id": "f2p-6",
      "title": "PUBG: Battlegrounds",
      "description": "Realistic Battle Royale experience with strategic gameplay",
      "price": 29.99,
      "image": "https://wallpapers.com/images/featured/pubg-4k-m7d01u319yw5wo0m.jpg",
      "developer": "PUBG Corporation",
      "publisher": "PUBG Corporation",
      "releaseDate": "2024-06-10",
      "genres": ["Free To Play", "Battle Royale", "Shooter"],
      "tags": ["Multiplayer", "Battle Royale", "Survival"],
      "rating": 4.5,
      "playerCount": 180000,
      "features": ["Realistic Combat", "Cross-platform", "Survival Mode"],
      "operatingSystem": ["Windows", "PlayStation", "Xbox"],
      "languages": ["English", "Spanish", "Russian"]
    },
    {
      "id": "f2p-7",
      "title": "Fall Guys",
      "description": "Fun and chaotic Battle Royale game with colorful, quirky characters",
      "price": 19.99,
      "image": "https://w0.peakpx.com/wallpaper/480/935/HD-wallpaper-poster-of-fall-guys.jpg",
      "developer": "Mediatonic",
      "publisher": "Devolver Digital",
      "releaseDate": "2024-08-05",
      "genres": ["Free To Play", "Party", "Battle Royale"],
      "tags": ["Multiplayer", "Casual", "Fun"],
      "rating": 4.3,
      "playerCount": 30000,
      "features": ["Cross-platform", "Fun Minigames", "Seasonal Events"],
      "operatingSystem": ["Windows", "PlayStation", "Switch"],
      "languages": ["English", "Spanish", "French"]
    },
    {
      "id": "f2p-8",
      "title": "Rocket League",
      "description": "Soccer with cars in this action-packed multiplayer game",
      "price": 20.00,
      "image": "https://i.ytimg.com/vi/SgSX3gOrj60/maxresdefault.jpg",
      "developer": "Psyonix",
      "publisher": "Psyonix",
      "releaseDate": "2024-07-01",
      "genres": ["Free To Play", "Sports", "Action"],
      "tags": ["Multiplayer", "Competitive", "Soccer"],
      "rating": 4.7,
      "playerCount": 70000,
      "features": ["Cross-platform", "Competitive Leagues", "Customizable Cars"],
      "operatingSystem": ["Windows", "PlayStation", "Xbox"],
      "languages": ["English", "Spanish", "French"]
    },
    {
      "id": "f2p-9",
      "title": "League of Legends",
      "description": "Strategic multiplayer online battle arena (MOBA) game",
      "price": 25.99,
      "image": "https://i.pinimg.com/originals/22/49/0d/22490db63367ba74ec73e9e913343f09.jpg",
      "developer": "Riot Games",
      "publisher": "Riot Games",
      "releaseDate": "2024-09-01",
      "genres": ["Free To Play", "MOBA", "Action"],
      "tags": ["Multiplayer", "Competitive", "Team-based"],
      "rating": 4.7,
      "playerCount": 80000,
      "features": ["Champion Abilities", "Ranked Mode", "Cross-platform"],
      "operatingSystem": ["Windows", "MacOS"],
      "languages": ["English", "Spanish", "French", "Chinese"]
    },
    // Add more free-to-play games...
  ],
  'early-access': [
      {
        id: 'ea-1',
        title: 'Space Pioneers',
        description: 'Build and manage your own space colony',
        price: 29.99,
        image: 'https://images.unsplash.com/photo-1614728263952-84ea256f9679?auto=format&fit=crop&w=800',
        developer: 'Stellar Studios',
        publisher: 'Space Games Inc',
        releaseDate: '2024-04-15',
        genres: ['Early Access', 'Simulation', 'Strategy'],
        tags: ['Space', 'Colony Sim', 'Resource Management'],
        rating: 4.2,
        playerCount: 8000,
        features: ['Regular Updates', 'Community Feedback', 'Mod Support'],
        operatingSystem: ['Windows'],
        languages: ['English', 'German']
      },
      {
        id: 'ea-2',
        title: 'Starbound',
        description: 'Explore the universe and create your own adventure',
        price: 19.99,
        image: 'https://images.unsplash.com/photo-1509086016933-5d7240b5a44f?auto=format&fit=crop&w=800',
        developer: 'Chucklefish',
        publisher: 'Chucklefish',
        releaseDate: '2024-02-10',
        genres: ['Early Access', 'Adventure', 'RPG'],
        tags: ['Exploration', 'Multiplayer', 'Sandbox'],
        rating: 4.5,
        playerCount: 12000,
        features: ['Procedural Generation', 'Co-op Play', 'Building Systems'],
        operatingSystem: ['Windows', 'MacOS', 'Linux'],
        languages: ['English', 'French', 'German']
      },
      {
        id: 'ea-3',
        title: 'No Man\'s Sky',
        description: 'Explore an infinite universe in this survival adventure game',
        price: 59.99,
        image: 'https://images.unsplash.com/photo-1501585965315-8c2d1f56fe1b?auto=format&fit=crop&w=800',
        developer: 'Hello Games',
        publisher: 'Hello Games',
        releaseDate: '2024-03-25',
        genres: ['Early Access', 'Adventure', 'Survival'],
        tags: ['Exploration', 'Survival', 'Multiplayer'],
        rating: 4.3,
        playerCount: 50000,
        features: ['Procedural Universe', 'Multiplayer', 'Crafting'],
        operatingSystem: ['Windows', 'PS4', 'Xbox'],
        languages: ['English', 'Spanish', 'Italian']
      },
      {
        id: 'ea-4',
        title: 'Planet Coaster',
        description: 'Create and manage your own theme park',
        price: 39.99,
        image: 'https://images.unsplash.com/photo-1518359943125-bf5e1d5b4f9d?auto=format&fit=crop&w=800',
        developer: 'Frontier Developments',
        publisher: 'Frontier Developments',
        releaseDate: '2024-05-01',
        genres: ['Early Access', 'Simulation', 'Strategy'],
        tags: ['Theme Park', 'Management', 'Creative'],
        rating: 4.6,
        playerCount: 7000,
        features: ['Customizable Rides', 'Creative Mode', 'Community Workshops'],
        operatingSystem: ['Windows'],
        languages: ['English', 'French', 'German']
      },
      {
        id: 'ea-5',
        title: 'Kerbal Space Program',
        description: 'Build spacecraft and explore space in this physics-based simulation',
        price: 39.99,
        image: 'https://images.unsplash.com/photo-1505593792093-79b0d5fcb1b9?auto=format&fit=crop&w=800',
        developer: 'Squad',
        publisher: 'Squad',
        releaseDate: '2024-07-15',
        genres: ['Early Access', 'Simulation', 'Strategy'],
        tags: ['Space', 'Physics', 'Engineering'],
        rating: 4.8,
        playerCount: 20000,
        features: ['Realistic Physics', 'Rocket Building', 'Space Exploration'],
        operatingSystem: ['Windows', 'MacOS'],
        languages: ['English', 'German', 'Spanish']
      },
      {
        id: 'ea-6',
        title: 'Satisfactory',
        description: 'Build and manage a factory on an alien planet',
        price: 29.99,
        image: 'https://images.unsplash.com/photo-1595492856257-cafdbb927d8f?auto=format&fit=crop&w=800',
        developer: 'Coffee Stain Studios',
        publisher: 'Coffee Stain Studios',
        releaseDate: '2024-08-01',
        genres: ['Early Access', 'Simulation', 'Strategy'],
        tags: ['Factory Building', 'Automation', 'Exploration'],
        rating: 4.7,
        playerCount: 15000,
        features: ['Co-op Multiplayer', 'Building Systems', 'Resource Management'],
        operatingSystem: ['Windows'],
        languages: ['English', 'Russian', 'Chinese']
      },
      {
        id: 'ea-7',
        title: 'The Forest',
        description: 'Survive and build in a mysterious forest after a plane crash',
        price: 19.99,
        image: 'https://images.unsplash.com/photo-1516847780919-8f6021f09e3e?auto=format&fit=crop&w=800',
        developer: 'Endnight Games',
        publisher: 'Endnight Games',
        releaseDate: '2024-06-12',
        genres: ['Early Access', 'Survival', 'Adventure'],
        tags: ['Survival', 'Co-op', 'Horror'],
        rating: 4.5,
        playerCount: 10000,
        features: ['Co-op Multiplayer', 'Crafting', 'Building'],
        operatingSystem: ['Windows', 'PS4'],
        languages: ['English', 'French', 'German']
      },
      {
        id: 'ea-8',
        title: 'Hunt: Showdown',
        description: 'Hunt down supernatural creatures in a dark and dangerous world',
        price: 39.99,
        image: 'https://images.unsplash.com/photo-1525387286254-5a76c28d7b9f?auto=format&fit=crop&w=800',
        developer: 'Crytek',
        publisher: 'Crytek',
        releaseDate: '2024-09-15',
        genres: ['Early Access', 'Shooter', 'Survival'],
        tags: ['Multiplayer', 'PvP', 'Horror'],
        rating: 4.4,
        playerCount: 25000,
        features: ['Hunt Creatures', 'PvP', 'Dark Atmosphere'],
        operatingSystem: ['Windows'],
        languages: ['English', 'French', 'Spanish']
      },
      {
        id: 'ea-9',
        title: 'Rust',
        description: 'Survive, craft, and build in a harsh open world environment',
        price: 39.99,
        image: 'https://images.unsplash.com/photo-1532635112-2908d4f2f7e0?auto=format&fit=crop&w=800',
        developer: 'Facepunch Studios',
        publisher: 'Facepunch Studios',
        releaseDate: '2024-10-01',
        genres: ['Early Access', 'Survival', 'Multiplayer'],
        tags: ['PvP', 'Crafting', 'Building'],
        rating: 4.6,
        playerCount: 50000,
        features: ['Multiplayer', 'Base Building', 'Crafting'],
        operatingSystem: ['Windows', 'MacOS'],
        languages: ['English', 'Spanish', 'Russian']
      }, 
    // Add more early access games...
  ],
  'action': [
      {
        id: 'act-1',
        title: 'Shadow Warriors',
        description: 'Epic martial arts action with supernatural powers',
        price: 49.99,
        image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800',
        developer: 'Dragon Studios',
        publisher: 'Action Games Co',
        releaseDate: '2024-02-20',
        genres: ['Action', 'Fighting', 'Martial Arts'],
        tags: ['Single Player', 'Combat', 'Story Rich'],
        rating: 4.7,
        playerCount: 15000,
        features: ['Complex Combat System', 'Character Progression', 'Multiple Endings'],
        operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
        languages: ['English', 'Japanese', 'Korean']
      },
      {
        id: 'act-2',
        title: 'Mortal Kombat 12',
        description: 'The ultimate fighting game with brutal combat and fatalities',
        price: 59.99,
        image: 'https://images.unsplash.com/photo-1579812343157-79a0d82c7f9b?auto=format&fit=crop&w=800',
        developer: 'NetherRealm Studios',
        publisher: 'Warner Bros. Interactive Entertainment',
        releaseDate: '2024-04-01',
        genres: ['Action', 'Fighting'],
        tags: ['Brutal Combat', 'Multiplayer', 'Fatalities'],
        rating: 4.8,
        playerCount: 30000,
        features: ['Multiplayer', 'Fatalities', 'Character Customization'],
        operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
        languages: ['English', 'Spanish', 'French']
      },
      {
        id: 'act-3',
        title: 'Tekken 8',
        description: 'The latest installment in the iconic fighting series',
        price: 59.99,
        image: 'https://images.unsplash.com/photo-1587956980743-7e5b6f9baf8d?auto=format&fit=crop&w=800',
        developer: 'Bandai Namco Entertainment',
        publisher: 'Bandai Namco Entertainment',
        releaseDate: '2024-05-15',
        genres: ['Action', 'Fighting'],
        tags: ['Multiplayer', 'Combo Fighting', 'Character Variety'],
        rating: 4.7,
        playerCount: 20000,
        features: ['Online Multiplayer', 'Character Customization', 'New Fighting Styles'],
        operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
        languages: ['English', 'Japanese', 'German']
      },
      {
        id: 'act-4',
        title: 'Street Fighter VI',
        description: 'The next chapter in the legendary Street Fighter franchise',
        price: 59.99,
        image: 'https://images.unsplash.com/photo-1579812343157-79a0d82c7f9b?auto=format&fit=crop&w=800',
        developer: 'Capcom',
        publisher: 'Capcom',
        releaseDate: '2024-06-10',
        genres: ['Action', 'Fighting'],
        tags: ['Multiplayer', 'Fighting Mechanics', 'Classic Characters'],
        rating: 4.6,
        playerCount: 25000,
        features: ['Online Multiplayer', 'Classic Mode', 'New Characters'],
        operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
        languages: ['English', 'French', 'Spanish']
      },
      {
        id: 'act-5',
        title: 'Dragon Ball FighterZ 2',
        description: 'Epic 2D fighting game featuring Dragon Ball Z characters',
        price: 49.99,
        image: 'https://images.unsplash.com/photo-1554251243-cb3e9b7d0d0f?auto=format&fit=crop&w=800',
        developer: 'Arc System Works',
        publisher: 'Bandai Namco Entertainment',
        releaseDate: '2024-07-05',
        genres: ['Action', 'Fighting'],
        tags: ['Anime', 'Multiplayer', 'Combo Fighting'],
        rating: 4.9,
        playerCount: 35000,
        features: ['Team Battles', 'Combo Fighting', 'Stunning Visuals'],
        operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
        languages: ['English', 'Japanese', 'Spanish']
      },
      {
        id: 'act-6',
        title: 'Injustice 3',
        description: 'Battle it out with DC superheroes and villains',
        price: 59.99,
        image: 'https://images.unsplash.com/photo-1588254060567-9e6f4d8f94a5?auto=format&fit=crop&w=800',
        developer: 'NetherRealm Studios',
        publisher: 'Warner Bros. Interactive Entertainment',
        releaseDate: '2024-08-10',
        genres: ['Action', 'Fighting'],
        tags: ['Superheroes', 'Multiplayer', 'Story Mode'],
        rating: 4.8,
        playerCount: 30000,
        features: ['Superhero Combat', 'Character Progression', 'Online Multiplayer'],
        operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
        languages: ['English', 'French', 'German']
      },
      {
        id: 'act-7',
        title: 'Soulcalibur VII',
        description: 'Classic weapon-based fighting with new characters and mechanics',
        price: 59.99,
        image: 'https://images.unsplash.com/photo-1575644059990-bf8b9eaa1f0f?auto=format&fit=crop&w=800',
        developer: 'Bandai Namco Entertainment',
        publisher: 'Bandai Namco Entertainment',
        releaseDate: '2024-09-01',
        genres: ['Action', 'Fighting'],
        tags: ['Weapon Combat', 'Multiplayer', 'Character Customization'],
        rating: 4.5,
        playerCount: 22000,
        features: ['Weapon-based Combat', 'Character Customization', 'Multiplayer'],
        operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
        languages: ['English', 'French', 'Italian']
      },
      {
        id: 'act-8',
        title: 'For Honor',
        description: 'A brutal medieval combat game with knights, samurais, and vikings',
        price: 49.99,
        image: 'https://images.unsplash.com/photo-1575644059990-bf8b9eaa1f0f?auto=format&fit=crop&w=800',
        developer: 'Ubisoft',
        publisher: 'Ubisoft',
        releaseDate: '2024-09-20',
        genres: ['Action', 'Fighting'],
        tags: ['Medieval Combat', 'Multiplayer', 'Strategy'],
        rating: 4.6,
        playerCount: 27000,
        features: ['Faction Wars', 'PvP', 'Combat Strategy'],
        operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
        languages: ['English', 'French', 'German']
      },
      {
        id: 'act-9',
        title: 'Dead or Alive 6',
        description: 'Fast-paced, action-packed fighting game with high-fidelity graphics',
        price: 49.99,
        image: 'https://images.unsplash.com/photo-1588254060567-9e6f4d8f94a5?auto=format&fit=crop&w=800',
        developer: 'Team Ninja',
        publisher: 'Koei Tecmo',
        releaseDate: '2024-10-01',
        genres: ['Action', 'Fighting'],
        tags: ['Fighting Mechanics', 'Multiplayer', 'Character Customization'],
        rating: 4.4,
        playerCount: 18000,
        features: ['Combo Fighting', 'Character Customization', 'Multiplayer'],
        operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
        languages: ['English', 'Japanese', 'Spanish']
      },   
    // Add more action games...
  ],
  'adventure': [
    {
      id: 'adv-1',
      title: 'Watch Dogs 2',
      description: 'Explore the open world of San Francisco in this action-adventure game',
      price: 39.99,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjAllJZmXfufR_et_wsLE5eV3V0O2QsKt36g&s',
      developer: 'Ubisoft Montreal',
      publisher: 'Ubisoft',
      releaseDate: '2016-11-15',
      genres: ['Adventure', 'Action', 'Open World'],
      tags: ['Story Rich', 'Atmospheric', 'Mystery'],
      rating: 4.6,
      playerCount: 12000,
      features: ['Open World', 'Rich Narrative', 'Hidden Secrets'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'French', 'Spanish']
    },
    {
      id: 'adv-2',
      title: 'Grand Theft Auto V',
      description: 'Experience the open world of Los Santos in this action-packed game',
      price: 59.99,
      image: 'https://wallpapers.com/images/featured/gta-5-qpjtjdxwbwrk4gyj.jpg',
      developer: 'Rockstar North',
      publisher: 'Rockstar Games',
      releaseDate: '2013-09-17',
      genres: ['Action', 'Adventure', 'Open World'],
      tags: ['Multiplayer', 'Story Rich', 'Crime'],
      rating: 4.9,
      playerCount: 300000,
      features: ['Multiplayer Mode', 'Heist Missions', 'Extensive Customization'],
      operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
      languages: ['English', 'Spanish', 'French', 'German']
    },
    {
      id: 'adv-3',
      title: 'Mumbai Gullies',
      description: 'Dive into the streets of Mumbai in this open-world action game',
      price: 49.99,
      image: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1569890/header.jpg?t=1709981409',
      developer: 'Mumbai Studios',
      publisher: 'Gully Games',
      releaseDate: '2024-05-01',
      genres: ['Action', 'Adventure', 'Open World'],
      tags: ['Story Rich', 'Urban Exploration', 'Crime'],
      rating: 4.7,
      playerCount: 20000,
      features: ['Open World Exploration', 'Dynamic NPCs', 'Customizable Vehicles'],
      operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
      languages: ['English', 'Hindi']
    },
    {
      id: 'adv-4',
      title: 'The Witcher 3: Wild Hunt',
      description: 'Embark on a journey as Geralt of Rivia in this epic fantasy RPG',
      price: 49.99,
      image: 'https://i.redd.it/5vax2xu1hpz41.jpg',
      developer: 'CD Projekt Red',
      publisher: 'CD Projekt',
      releaseDate: '2015-05-19',
      genres: ['RPG', 'Action', 'Fantasy'],
      tags: ['Story Rich', 'Open World', 'Adventure'],
      rating: 4.9,
      playerCount: 100000,
      features: ['Expansive World', 'Choices Matter', 'Multiple Endings'],
      operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
      languages: ['English', 'Polish', 'French', 'Spanish']
    },
    {
      id: 'adv-5',
      title: 'Red Dead Redemption 2',
      description: 'Live the life of an outlaw in this action-adventure western',
      price: 59.99,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMPOSaHvVOC4zqW7Zw5pv7iO5sJKNjj9iikQ&s',
      developer: 'Rockstar Games',
      publisher: 'Rockstar Games',
      releaseDate: '2018-10-26',
      genres: ['Action', 'Adventure', 'Western'],
      tags: ['Open World', 'Story Rich', 'Exploration'],
      rating: 4.8,
      playerCount: 50000,
      features: ['Dynamic Weather', 'Rich Story', 'Multiplayer Mode'],
      operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
      languages: ['English', 'French', 'German', 'Spanish']
    },
    {
      id: 'adv-6',
      title: 'Cyberpunk 2077',
      description: 'Enter the neon-lit world of Night City in this futuristic RPG',
      price: 39.99,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCCqrzdeUT-9O9weROc5UItFXWVUbKDobxvA&s',
      developer: 'CD Projekt Red',
      publisher: 'CD Projekt',
      releaseDate: '2020-12-10',
      genres: ['Action', 'Adventure', 'RPG'],
      tags: ['Open World', 'Cyberpunk', 'Story Rich'],
      rating: 4.7,
      playerCount: 40000,
      features: ['Open World', 'Character Customization', 'Branching Storylines'],
      operatingSystem: ['Windows', 'PlayStation'],
      languages: ['English', 'French', 'Spanish']
    }
    
    // Add more adventure games...
  ],
  'casual': [
    {
      id: 'cas-1',
      title: 'Puzzle Paradise',
      description: 'Relax and solve beautiful puzzles in a tranquil setting',
      price: 9.99,
      image: 'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800',
      developer: 'Calm Games',
      publisher: 'Relax Studios',
      releaseDate: '2024-02-01',
      genres: ['Casual', 'Puzzle'],
      tags: ['Relaxing', 'Single Player', 'Family Friendly'],
      rating: 4.3,
      playerCount: 5000,
      features: ['Hundreds of Puzzles', 'Soothing Music', 'Offline Play'],
      operatingSystem: ['Windows', 'MacOS', 'Mobile'],
      languages: ['English', 'Spanish', 'French']
    },
    {
      id: 'cas-2',
      title: 'Candy Crush Saga',
      description: 'Match colorful candies to progress through levels in this addictive puzzle game',
      price: 0,
      image: 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Candy_Crush_Saga_Logo.png',
      developer: 'King',
      publisher: 'King',
      releaseDate: '2012-04-12',
      genres: ['Casual', 'Puzzle'],
      tags: ['Match-3', 'Addictive', 'Free-to-play'],
      rating: 4.6,
      playerCount: 500000,
      features: ['Daily Challenges', 'Social Integration', 'Power-ups'],
      operatingSystem: ['Windows', 'iOS', 'Android'],
      languages: ['English', 'Spanish', 'French', 'German']
    },
    {
      id: 'cas-3',
      title: 'FarmVille 2',
      description: 'Build and manage your farm while completing fun challenges',
      price: 0,
      image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Farmville_2_Logo.png',
      developer: 'Zynga',
      publisher: 'Zynga',
      releaseDate: '2012-09-25',
      genres: ['Casual', 'Simulation'],
      tags: ['Farm', 'Management', 'Free-to-play'],
      rating: 4.5,
      playerCount: 150000,
      features: ['Cooperative Farming', 'Seasonal Events', 'Animal Breeding'],
      operatingSystem: ['Windows', 'iOS', 'Android'],
      languages: ['English', 'Spanish', 'French']
    },
    {
      id: 'cas-4',
      title: 'Angry Birds 2',
      description: 'Launch birds with unique powers to defeat pigs and save your eggs',
      price: 0,
      image: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Angry_Birds_2_Logo.png',
      developer: 'Rovio Entertainment',
      publisher: 'Rovio Entertainment',
      releaseDate: '2015-07-30',
      genres: ['Casual', 'Puzzle'],
      tags: ['Physics-based', 'Fun', 'Free-to-play'],
      rating: 4.4,
      playerCount: 100000,
      features: ['Multiple Birds', 'Challenging Levels', 'Boss Fights'],
      operatingSystem: ['iOS', 'Android'],
      languages: ['English', 'Spanish', 'French', 'German']
    },
    {
      id: 'cas-5',
      title: 'Bejeweled Blitz',
      description: 'Match gems in this fast-paced puzzle game to earn high scores',
      price: 0,
      image: 'https://upload.wikimedia.org/wikipedia/commons/1/14/Bejeweled_Blitz_Logo.png',
      developer: 'PopCap Games',
      publisher: 'PopCap Games',
      releaseDate: '2010-11-15',
      genres: ['Casual', 'Puzzle'],
      tags: ['Match-3', 'High Scores', 'Free-to-play'],
      rating: 4.7,
      playerCount: 200000,
      features: ['Timed Gameplay', 'Power-ups', 'Leaderboard'],
      operatingSystem: ['Windows', 'iOS', 'Android'],
      languages: ['English', 'Spanish', 'French']
    }    
    // Add more casual games...
  ],
  'indie': [
    {
      id: 'ind-1',
      title: 'Pixel Adventure',
      description: 'A charming pixel art platformer with a heartwarming story',
      price: 14.99,
      image: 'https://images.unsplash.com/photo-1596496050672-b0fefd046baf?auto=format&fit=crop&w=800',
      developer: 'Indie Devs United',
      publisher: 'Pixel Studios',
      releaseDate: '2024-03-10',
      genres: ['Indie', 'Platformer', 'Adventure'],
      tags: ['Pixel Art', 'Story Rich', 'Exploration'],
      rating: 4.7,
      playerCount: 8000,
      features: ['Unique Art Style', 'Emotional Story', 'Challenging Levels'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'Japanese', 'German']
    },
    {
      id: 'ind-2',
      title: 'Stardew Valley',
      description: 'A farming simulator with RPG elements and a focus on community and exploration',
      price: 14.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Stardew_Valley_logo.png',
      developer: 'ConcernedApe',
      publisher: 'ConcernedApe',
      releaseDate: '2016-02-26',
      genres: ['Indie', 'Simulation', 'RPG'],
      tags: ['Farming', 'Co-op', 'RPG'],
      rating: 4.9,
      playerCount: 1000000,
      features: ['Multiplayer', 'Seasonal Events', 'Farm Customization'],
      operatingSystem: ['Windows', 'MacOS', 'Linux', 'iOS', 'Android'],
      languages: ['English', 'Spanish', 'French', 'German']
    },
    {
      id: 'ind-3',
      title: 'Hollow Knight',
      description: 'A dark, challenging Metroidvania game set in a beautifully hand-drawn world',
      price: 14.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Hollow_Knight_logo.png',
      developer: 'Team Cherry',
      publisher: 'Team Cherry',
      releaseDate: '2017-02-24',
      genres: ['Indie', 'Action', 'Adventure'],
      tags: ['Metroidvania', 'Challenging', 'Exploration'],
      rating: 4.8,
      playerCount: 500000,
      features: ['Fluid Combat', 'Intricate World', 'Boss Fights'],
      operatingSystem: ['Windows', 'MacOS', 'Linux'],
      languages: ['English', 'Spanish', 'French', 'German']
    },
    {
      id: 'ind-4',
      title: 'Celeste',
      description: 'A challenging platformer with an emotional story about overcoming personal struggles',
      price: 19.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Celeste_logo.png',
      developer: 'Maddy Makes Games',
      publisher: 'Maddy Makes Games',
      releaseDate: '2018-01-25',
      genres: ['Indie', 'Platformer'],
      tags: ['Challenging', 'Story Rich', 'Emotional'],
      rating: 4.9,
      playerCount: 300000,
      features: ['Precise Platforming', 'Beautiful Soundtrack', 'Deep Story'],
      operatingSystem: ['Windows', 'MacOS', 'Linux'],
      languages: ['English', 'Spanish', 'French', 'German']
    },
    {
      id: 'ind-5',
      title: 'Dead Cells',
      description: 'A rogue-like, Metroidvania inspired action-platformer with procedurally generated levels',
      price: 24.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/c/c0/Dead_Cells_logo.png',
      developer: 'Motion Twin',
      publisher: 'Motion Twin',
      releaseDate: '2018-08-07',
      genres: ['Indie', 'Action', 'Roguelike'],
      tags: ['Rogue-like', 'Action', 'Exploration'],
      rating: 4.8,
      playerCount: 400000,
      features: ['Procedural Generation', 'Challenging Combat', 'Multiple Weapons'],
      operatingSystem: ['Windows', 'MacOS', 'Linux'],
      languages: ['English', 'Spanish', 'French', 'German']
    },
    {
      id: 'ind-6',
      title: 'The Witness',
      description: 'A first-person puzzle game set on a mysterious island filled with challenging puzzles',
      price: 29.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/The_Witness_logo.png',
      developer: 'Jonathan Blow',
      publisher: 'Thekla, Inc.',
      releaseDate: '2016-01-26',
      genres: ['Indie', 'Puzzle', 'Adventure'],
      tags: ['Puzzle', 'Exploration', 'Mystery'],
      rating: 4.6,
      playerCount: 200000,
      features: ['First-Person Exploration', 'Challenging Puzzles', 'Immersive World'],
      operatingSystem: ['Windows', 'MacOS', 'Linux', 'iOS'],
      languages: ['English', 'Spanish', 'French', 'German']
    }    
    // Add more indie games...
  ],
  'mmo': [
    {
      id: 'mm-1',
      title: 'Guilds of Eternity',
      description: 'Join guilds and conquer vast lands in this epic MMO',
      price: 0,
      image: 'https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?auto=format&fit=crop&w=800',
      developer: 'Eternal Studios',
      publisher: 'MMO Inc',
      releaseDate: '2024-06-01',
      genres: ['Massively Multiplayer', 'RPG'],
      tags: ['Guilds', 'PvP', 'Open World'],
      rating: 4.4,
      playerCount: 100000,
      features: ['Player Guilds', 'Massive PvP Battles', 'Dynamic Events'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'Spanish', 'Russian']
    },
    {
      id: 'mm-2',
      title: 'World of Warcraft',
      description: 'A classic MMORPG where players can explore a vast world, complete quests, and battle fierce enemies',
      price: 39.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/World_of_Warcraft_logo.svg',
      developer: 'Blizzard Entertainment',
      publisher: 'Blizzard Entertainment',
      releaseDate: '2004-11-23',
      genres: ['Massively Multiplayer', 'RPG'],
      tags: ['PvP', 'Raids', 'Dungeons'],
      rating: 4.8,
      playerCount: 5000000,
      features: ['Raids', 'PvP Arenas', 'Expansions'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'Spanish', 'French', 'German']
    },
    {
      id: 'mm-3',
      title: 'Final Fantasy XIV',
      description: 'An MMORPG set in the Final Fantasy universe with rich storylines, dungeons, and large-scale raids',
      price: 19.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Final_Fantasy_XIV_Logo.svg',
      developer: 'Square Enix',
      publisher: 'Square Enix',
      releaseDate: '2013-08-27',
      genres: ['Massively Multiplayer', 'RPG'],
      tags: ['PvE', 'Raids', 'Story Rich'],
      rating: 4.9,
      playerCount: 3000000,
      features: ['Expansions', 'Dungeons', 'PvP'],
      operatingSystem: ['Windows', 'MacOS', 'PlayStation'],
      languages: ['English', 'Japanese', 'French', 'German']
    },
    {
      id: 'mm-4',
      title: 'The Elder Scrolls Online',
      description: 'An open-world MMORPG set in the Elder Scrolls universe with a deep story and exploration',
      price: 29.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/The_Elder_Scrolls_Online_logo.svg',
      developer: 'ZeniMax Online Studios',
      publisher: 'Bethesda Softworks',
      releaseDate: '2014-04-04',
      genres: ['Massively Multiplayer', 'RPG'],
      tags: ['PvE', 'PvP', 'Exploration'],
      rating: 4.6,
      playerCount: 2000000,
      features: ['PvP', 'Expansions', 'Raids'],
      operatingSystem: ['Windows', 'MacOS', 'PlayStation', 'Xbox'],
      languages: ['English', 'Spanish', 'German', 'French']
    },
    {
      id: 'mm-5',
      title: 'Guild Wars 2',
      description: 'An MMORPG with dynamic events, a unique combat system, and a focus on player choice',
      price: 29.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Guild_Wars_2_logo.svg',
      developer: 'ArenaNet',
      publisher: 'NCSoft',
      releaseDate: '2012-08-28',
      genres: ['Massively Multiplayer', 'RPG'],
      tags: ['PvP', 'Dynamic Events', 'Open World'],
      rating: 4.7,
      playerCount: 1500000,
      features: ['Dynamic Events', 'PvP', 'Expansions'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'Spanish', 'French', 'German']
    },
    {
      id: 'mm-6',
      title: 'Black Desert Online',
      description: 'A visually stunning MMORPG with fast-paced combat, crafting, and a vast world to explore',
      price: 29.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Black_Desert_Online_logo.svg',
      developer: 'Pearl Abyss',
      publisher: 'Pearl Abyss',
      releaseDate: '2015-12-22',
      genres: ['Massively Multiplayer', 'RPG'],
      tags: ['PvP', 'Crafting', 'Open World'],
      rating: 4.5,
      playerCount: 1000000,
      features: ['PvP', 'Crafting', 'Expansions'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'Spanish', 'German', 'French']
    }
    
    // Add more massively multiplayer games...
  ],
  'racing': [
    {
      id: 'rac-1',
      title: 'Speed Kings',
      description: 'Experience the thrill of high-speed racing',
      price: 59.99,
      image: 'https://images.unsplash.com/photo-1558981405-5c06e1b8b97e?auto=format&fit=crop&w=800',
      developer: 'Speed Studios',
      publisher: 'Racing Games Co',
      releaseDate: '2024-05-15',
      genres: ['Racing', 'Sports'],
      tags: ['High Speed', 'Multiplayer', 'Realistic Physics'],
      rating: 4.8,
      playerCount: 20000,
      features: ['Realistic Cars', 'Online Multiplayer', 'Track Editor'],
      operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
      languages: ['English', 'French', 'German']
    },
    // Add more racing games...
  ],
  'rpg': [
    {
      id: 'rpg-1',
      title: 'Legends of Avalon',
      description: 'Embark on a magical journey in a mystical land',
      price: 49.99,
      image: 'https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?auto=format&fit=crop&w=800',
      developer: 'Mystic Studios',
      publisher: 'RPG Worlds',
      releaseDate: '2024-07-01',
      genres: ['RPG', 'Fantasy'],
      tags: ['Magic', 'Quests', 'Open World'],
      rating: 4.9,
      playerCount: 15000,
      features: ['Rich Storyline', 'Character Customization', 'Expansive World'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'Japanese', 'Korean']
    },
    // Add more RPG games...
  ],
  'simulation': [
    {
      id: 'sim-1',
      title: 'City Architect',
      description: 'Design and build the city of your dreams',
      price: 29.99,
      image: 'https://images.unsplash.com/photo-1603306832825-7dbf1c7b8d04?auto=format&fit=crop&w=800',
      developer: 'Urban Studios',
      publisher: 'Simulation Games Co',
      releaseDate: '2024-08-10',
      genres: ['Simulation', 'Strategy'],
      tags: ['City Building', 'Resource Management', 'Creative'],
      rating: 4.5,
      playerCount: 10000,
      features: ['Dynamic Weather', 'Mod Support', 'Realistic Economy'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'German', 'Spanish']
    },
    {
      id: 'sim-2',
      title: 'The Sims 4',
      description: 'Create and control people in a virtual world where you can build homes, form relationships, and live out life',
      price: 39.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/The_Sims_4_logo.svg',
      developer: 'Maxis',
      publisher: 'Electronic Arts',
      releaseDate: '2014-09-02',
      genres: ['Simulation', 'Life Simulation'],
      tags: ['Life Simulation', 'Building', 'Social'],
      rating: 4.7,
      playerCount: 10000000,
      features: ['Character Customization', 'Building', 'Expansions'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'Spanish', 'French', 'German']
    },
    {
      id: 'sim-3',
      title: 'Planet Coaster',
      description: 'Design and manage your own theme park with custom roller coasters and attractions',
      price: 29.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Planet_Coaster_logo.svg',
      developer: 'Frontier Developments',
      publisher: 'Frontier Developments',
      releaseDate: '2016-11-17',
      genres: ['Simulation', 'Strategy'],
      tags: ['Theme Park', 'Building', 'Creative'],
      rating: 4.6,
      playerCount: 800000,
      features: ['Custom Roller Coasters', 'Theme Park Management', 'Expansions'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'German', 'French']
    },
    {
      id: 'sim-4',
      title: 'SimCity 5',
      description: 'Create and manage a city from scratch, making decisions on infrastructure, economy, and citizen needs',
      price: 19.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/5/57/SimCity_2013_Logo.svg',
      developer: 'Maxis',
      publisher: 'Electronic Arts',
      releaseDate: '2013-03-05',
      genres: ['Simulation', 'Strategy'],
      tags: ['City Building', 'Economy', 'Management'],
      rating: 4.2,
      playerCount: 3000000,
      features: ['City Management', 'Economy', 'Disasters'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'French', 'German']
    },
    {
      id: 'sim-5',
      title: 'Farming Simulator 22',
      description: 'Manage your own farm, grow crops, raise animals, and run your business in this realistic farming simulation',
      price: 49.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Farming_Simulator_22_logo.svg',
      developer: 'GIANTS Software',
      publisher: 'GIANTS Software',
      releaseDate: '2021-11-22',
      genres: ['Simulation', 'Farming'],
      tags: ['Farming', 'Business', 'Open World'],
      rating: 4.5,
      playerCount: 500000,
      features: ['Farming', 'Vehicle Customization', 'Multiplayer'],
      operatingSystem: ['Windows', 'MacOS', 'PlayStation', 'Xbox'],
      languages: ['English', 'Spanish', 'German', 'French']
    },
    {
      id: 'sim-6',
      title: 'RollerCoaster Tycoon 2',
      description: 'Build and manage your own theme park with roller coasters, attractions, and businesses',
      price: 9.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/0/01/RollerCoaster_Tycoon_2_Logo.svg',
      developer: 'Chris Sawyer Productions',
      publisher: 'Infogrames',
      releaseDate: '2002-10-28',
      genres: ['Simulation', 'Strategy'],
      tags: ['Theme Park', 'Management', 'Creative'],
      rating: 4.4,
      playerCount: 500000,
      features: ['Roller Coaster Design', 'Park Management', 'Expansion Packs'],
      operatingSystem: ['Windows'],
      languages: ['English', 'German', 'French']
    },    
    // Add more simulation games...
  ],
  'sports': [
    {
      id: 'spo-1',
      title: 'Pro Football 2024',
      description: 'Lead your team to glory in this realistic football simulation',
      price: 49.99,
      image: 'https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?auto=format&fit=crop&w=800',
      developer: 'Sports Pro Studios',
      publisher: 'Sports Games Inc',
      releaseDate: '2024-09-01',
      genres: ['Sports', 'Simulation'],
      tags: ['Football', 'Team Management', 'Multiplayer'],
      rating: 4.6,
      playerCount: 20000,
      features: ['Realistic Physics', 'Online Multiplayer', 'Custom Teams'],
      operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
      languages: ['English', 'French', 'Italian']
    },
    {
      id: 'spo-2',
      title: 'FIFA 24',
      description: 'The ultimate football experience with new mechanics and real-life teams',
      price: 59.99,
      image: 'https://images5.alphacoders.com/133/1332401.jpeg',
      developer: 'EA Sports',
      publisher: 'Electronic Arts',
      releaseDate: '2024-09-30',
      genres: ['Sports', 'Simulation'],
      tags: ['Football', 'Multiplayer', 'Realism'],
      rating: 4.8,
      playerCount: 500000,
      features: ['Realistic Animations', 'Online Multiplayer', 'New Career Mode'],
      operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
      languages: ['English', 'Spanish', 'French', 'German']
    },
    {
      id: 'spo-3',
      title: 'NBA 2K24',
      description: 'Take control of the court in this immersive basketball simulation',
      price: 59.99,
      image: 'https://4kwallpapers.com/images/walls/thumbs/12701.jpg',
      developer: 'Visual Concepts',
      publisher: '2K Sports',
      releaseDate: '2024-09-15',
      genres: ['Sports', 'Simulation'],
      tags: ['Basketball', 'Multiplayer', 'Career Mode'],
      rating: 4.7,
      playerCount: 300000,
      features: ['Realistic Gameplay', 'Online Multiplayer', 'MyCareer Mode'],
      operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
      languages: ['English', 'Spanish', 'French']
    },
    {
      id: 'spo-4',
      title: 'Madden NFL 24',
      description: 'Experience the thrill of American football with the latest Madden game',
      price: 59.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Madden_NFL_24_logo.svg',
      developer: 'EA Sports',
      publisher: 'Electronic Arts',
      releaseDate: '2024-08-20',
      genres: ['Sports', 'Simulation'],
      tags: ['Football', 'Team Management', 'Multiplayer'],
      rating: 4.5,
      playerCount: 100000,
      features: ['Realistic Physics', 'Team Management', 'Online Multiplayer'],
      operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
      languages: ['English', 'Spanish', 'German']
    },
    {
      id: 'spo-5',
      title: 'Cricket 24',
      description: 'Step into the world of cricket and experience the most realistic cricketing action ever',
      price: 49.99,
      image: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2358260/capsule_616x353.jpg?t=1725870557',
      developer: 'Big Ant Studios',
      publisher: 'Big Ant Studios',
      releaseDate: '2023-10-05',
      genres: ['Sports', 'Simulation'],
      tags: ['Cricket', 'Multiplayer'],
      rating: 4.6,
      playerCount: 50000,
      features: ['Realistic Cricket', 'Multiplayer', 'Create a Superstar'],
      operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
      languages: ['English']
    },
    {
      id: 'spo-6',
      title: 'F1 2024',
      description: 'Get behind the wheel and race in the world’s most prestigious motorsport',
      price: 69.99,
      image: 'https://pcoptimizedsettings.com/wp-content/uploads/2024/06/compress_F1-24-Game-Header.jpg',
      developer: 'Codemasters',
      publisher: 'EA Sports',
      releaseDate: '2024-06-12',
      genres: ['Sports', 'Racing'],
      tags: ['Formula 1', 'Racing', 'Simulation'],
      rating: 4.7,
      playerCount: 150000,
      features: ['Realistic Racing', 'Career Mode', 'Multiplayer'],
      operatingSystem: ['Windows', 'PlayStation', 'Xbox'],
      languages: ['English', 'French', 'German', 'Spanish']
    },    
    // Add more sports games...
  ],
  'strategy': [
    {
      id: 'str-1',
      title: 'Empire Builders',
      description: 'Conquer and manage your empire in this strategy game',
      price: 39.99,
      image: 'https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?auto=format&fit=crop&w=800',
      developer: 'Strategic Studios',
      publisher: 'Strategy Games Co',
      releaseDate: '2024-10-01',
      genres: ['Strategy', 'Simulation'],
      tags: ['Empire Building', 'Resource Management', 'Tactical Combat'],
      rating: 4.7,
      playerCount: 15000,
      features: ['Expansive Maps', 'Multiplayer', 'AI Opponents'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'Russian', 'Chinese']
    },
    {
      id: 'str-2',
      title: 'Civilization VI',
      description: 'Build your civilization from the ground up and lead it to greatness',
      price: 59.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/3/33/Civilization_VI_Logo.svg',
      developer: 'Firaxis Games',
      publisher: '2K Games',
      releaseDate: '2024-10-15',
      genres: ['Strategy', 'Simulation'],
      tags: ['Empire Building', 'Turn-Based', 'Multiplayer'],
      rating: 4.8,
      playerCount: 100000,
      features: ['Multiplayer', 'Tactical Combat', 'Multiple Civilizations'],
      operatingSystem: ['Windows', 'MacOS', 'Linux'],
      languages: ['English', 'Spanish', 'French', 'German']
    },
    {
      id: 'str-3',
      title: 'Age of Empires IV',
      description: 'Build, conquer, and dominate in this real-time strategy game',
      price: 49.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Age_of_Empires_IV_logo.svg',
      developer: 'Relic Entertainment',
      publisher: 'Xbox Game Studios',
      releaseDate: '2024-09-15',
      genres: ['Strategy', 'Real-Time'],
      tags: ['Empire Building', 'Resource Management', 'Multiplayer'],
      rating: 4.6,
      playerCount: 80000,
      features: ['Multiplayer', 'Historical Campaigns', 'AI Opponents'],
      operatingSystem: ['Windows'],
      languages: ['English', 'French', 'Spanish']
    },
    {
      id: 'str-4',
      title: 'Total War: Warhammer III',
      description: 'Lead your army to victory in this fantasy strategy game',
      price: 59.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/9/92/Total_War_Warhammer_III_logo.svg',
      developer: 'Creative Assembly',
      publisher: 'SEGA',
      releaseDate: '2024-07-12',
      genres: ['Strategy', 'Fantasy'],
      tags: ['Empire Building', 'Tactical Combat', 'Fantasy'],
      rating: 4.7,
      playerCount: 60000,
      features: ['Multiplayer', 'Campaign Mode', 'Fantasy Factions'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'German', 'French']
    },
    {
      id: 'str-5',
      title: 'SimCity 2024',
      description: 'Create and manage your own city in this classic city-building simulator',
      price: 49.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/SimCity_2013_logo.svg',
      developer: 'Maxis',
      publisher: 'Electronic Arts',
      releaseDate: '2024-08-25',
      genres: ['Simulation', 'Strategy'],
      tags: ['City Building', 'Resource Management', 'Multiplayer'],
      rating: 4.5,
      playerCount: 50000,
      features: ['City Building', 'Multiplayer', 'Realistic Economy'],
      operatingSystem: ['Windows', 'MacOS'],
      languages: ['English', 'Spanish', 'French']
    },
    {
      id: 'str-6',
      title: 'Command & Conquer Remastered',
      description: 'Experience the classic real-time strategy game with updated graphics and gameplay',
      price: 29.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Command_and_Conquer_Remastered_Collection_logo.svg',
      developer: 'Petroglyph Games',
      publisher: 'Electronic Arts',
      releaseDate: '2024-05-01',
      genres: ['Strategy', 'Real-Time'],
      tags: ['Real-Time Strategy', 'Multiplayer', 'Classic'],
      rating: 4.6,
      playerCount: 40000,
      features: ['Remastered Graphics', 'Multiplayer', 'Classic Gameplay'],
      operatingSystem: ['Windows'],
      languages: ['English', 'German', 'French']
    },    
    // Add more strategy games...
  ]
};

export function GenrePage() {
  const { genre } = useParams();
  const genreKey = genre as keyof typeof GENRE_GAMES;
  const games = GENRE_GAMES[genreKey] || [];

  const genreName = genre
    ?.split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');

  return (
    <div className="max-w-7xl mx-auto px-4 py-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-2">{genreName} Games</h1>
        <p className="text-gray-400">Discover the best {genreName} games</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {games.map((game) => (
          <GameCard key={game.id} game={game} />
        ))}
      </div>

      {games.length === 0 && (
        <div className="text-center py-12">
          <p className="text-gray-400">No games found in this genre.</p>
        </div>
      )}
    </div>
  );
}